# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "simplexmap"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template_toolkit:
    start_tag: '<%'
    end_tag:   '%>'

# session information
# eventually should be a real database!
session: YAML
session_dir: /tmp/simplexmap-sessions

plugins:
    Database:
        driver:        'mysql'
        database:      'simplexmap'
        log_queries:   1
        host:          'localhost'
#        username:      'simplexmap'
#        password:      'radiomapper'
        username:      'root'
        password:      'sqlpass'
        on_connect_do: "SET SQL_MODE='TRADITIONAL'"

serializer: JSON
